### ISSUE TITLE
Pygments import error

### ISSUE THREAD

**Issue by hsingh23** [tmbb/SyntaxHighlight#4]
I get this error message on launch of anki.
An error occurred in an add-on. Please contact the add-on author.

/home/user/Anki/addons/code_highlight_addon/pygments/plugin.py:39: UserWarning: Module pygments was already imported from /home/user/Anki/addons/code_highlight_addon/pygments/**init**.pyc, but /usr/lib/python2.7/dist-packages is being added to sys.path
  import pkg_resources

**Comment by ghost** [comment]
Hello Tiago, could we be lucky to have a fix, if you have some spare time? You add-on is doing great, minus the warning message that pops up every time we launch Anki2. Thank you.

**Comment by willprice** [comment]
Hi nomnex, presumably you've already got pygments installed as that's what the error indicates. I too suffered from this error until I deleted the pygments folder in the code_highlight_addon folder, this fixes the issue with it conflicting with the system pygments package.

**Comment by ghost** [comment]
thanks for the feedback and sorry for the delay. if I remove the pygments folder in the addon I have another type of error message

error msg with the pygments folder:

```
An error occurred in an add-on.
Please post on the add-on forum:
https://groups.google.com/forum/#!forum/anki-addons

/home/mt/Anki/addons/code_highlight_addon/pygments/plugin.py:39: UserWarning: Module anki was already imported from /usr/share/anki/anki/__init__.py, but /usr/lib/python2.7/site-packages is being added to sys.path
  import pkg_resources
```

error message with the pygmens folder removed:

```
An error occurred in an add-on.
Please post on the add-on forum:
https://groups.google.com/forum/#!forum/anki-addons

Traceback (most recent call last):
  File "/usr/share/anki/aqt/addons.py", line 39, in loadAddons
    __import__(file.replace(".py", ""))
  File "/home/mt/Anki/addons/Syntax Highlighting for Code.py", line 2, in <module>
    import code_highlight_addon.code_highlight_addon
  File "/home/mt/Anki/addons/code_highlight_addon/code_highlight_addon.py", line 199, in <module>
    from pygments import highlight
ImportError: No module named pygments
```

**Comment by willprice** [comment]
Hi Nomnex, you have a different error to the one initially posted. In the intial post _pygments_ has been imported twice, your first error message indicates that _anki_ (the module) has been imported twice. What version of Anki are you running? If it's not the most recent, could you try using that? 
What's the python version?

**Comment by ghost** [comment]
Python 2.7.1 and anki 2.0.9 beta on Fedora Linux 15. You are right; after reading you message, I removed the anki 1.2.8 package from my distribution . I don't have this error message anymore when I start Anki 2. thank you.

**Comment by willprice** [comment]
Glad I could help!

On 3 June 2013 16:11, nomnex notifications@github.com wrote:

> Python 2.7.1 and anki 2.0.9 beta on Fedora Linux 15. You are right; after
> reading you message, I removed the anki 1.2.8 package from my distribution
> . I don't have this error message anymore when I start Anki 2. thank you.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/tmbb/SyntaxHighlight/issues/4#issuecomment-18847811
> .

## 

Will
